[package]
name = "infinitedsp-core"
authors = ["Fredrik Andersson <fredrikandersson@mac.com>"]
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "A modular audio DSP library for synthesis and effects."
repository = "https://github.com/Na1w/infinitedsp/"
readme = "README.md"
keywords = ["audio", "dsp", "synthesis", "effects", "no_std"]
categories = ["multimedia::audio", "embedded", "no-std"]
exclude = ["assets/audio/*", ".idea/*"]

[workspace]
members = [
    ".",
    "examples_app",
]

[features]
default = []
debug_visualize = []

[dependencies]
wide = { version = "1.1.1", default-features = false }
microfft = "0.6.0"
num-complex = { version = "0.4", default-features = false, features = ["libm"] }
libm = "0.2"
